### ISSUE TITLE
Геттеры/сеттеры

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [danilovvvladimir/TL-Practice-2023#16]
https://github.com/danilovvvladimir/TL-Practice-2023/blob/a3fcc9bdf8d8021c0eaf195be79ab031d0e2a2f5/hw-2/Shapes/Shapes/Shapes/Square.cs#L16-L29

В C# вместо методов геттеров/сеттеров используются свойства. Это упрощает работу с классом

**Comment by danilovvvladimir** [comment]
Поправил все issues, переработал механику построения треугольника (теперь создание не через точки, а через длины сторон + замена методов геттеров сеттеров на свойства во всех классах)
