### ISSUE TITLE
Подписи к импортам

### ISSUE THREAD

**Issue by AkshachRd** [danilovvvladimir/TL-Practice-2023#33]
Привет!
https://github.com/danilovvvladimir/TL-Practice-2023/blob/e1b8cc4dccc294dd5c31ecbbdeecd571caacbd91/hw-7/src/App.tsx#L1-L9
Зачем они нужны вообще? Ты их сам пишешь?
Импорты в целом нужны не нам, а сборщику, чтобы он собрал. На эти подписи в коде в итоге никто смотреть не будет, так что лучше будет убрать.

**Comment by danilovvvladimir** [comment]
Привет!
Подписи идут со сниппета создания компонента, сделал себе для упрощения работы и аккуратного кода.
