### ISSUE TITLE
Вычисления и магические числа

### ISSUE THREAD

**Issue by AkshachRd** [danilovvvladimir/TL-Practice-2023#43]
https://github.com/danilovvvladimir/TL-Practice-2023/blob/b483143380dd989d7d2dade773d6b94b6189f331/hw-7/src/components/UI/RangeInput/RangeInput.tsx#L16-L38
Почему ты деструктуризовал все остальные пропсы, а лишь `value`, `onChange` и `name` оставил в `props`?)
Нужно все вычисления `width`, `length` и определение `active` или не `active` вынести просто в переменные в компоненте, которые будут вычисляться при каждом рендере.
Согласись, что
```ts
const trackWidth = ((value - min) / (max - min)) * 100;
```
будет понятнее

**Comment by danilovvvladimir** [comment]
О, согласен, вынеся вычисления выглядит покруче.
Исправил.
