### ISSUE TITLE
Ошибка форматирования

### ISSUE THREAD

**Issue by AkshachRd** [danilovvvladimir/TL-Practice-2023#44]
https://github.com/danilovvvladimir/TL-Practice-2023/blob/b483143380dd989d7d2dade773d6b94b6189f331/hw-7/src/components/SingleReview/SingleReview.tsx#L15-L26
Ладно, не форматирования)
Очень несемантическая верстка. Я запутался что кто где. Хорошие теги пропиши

**Comment by danilovvvladimir** [comment]
Добавил семантики - текст отзыва в параграф, сам review в article.
