### ISSUE TITLE
Неверная логика отображения отзывов

### ISSUE THREAD

**Issue by AkshachRd** [danilovvvladimir/TL-Practice-2023#45]
https://github.com/danilovvvladimir/TL-Practice-2023/blob/b483143380dd989d7d2dade773d6b94b6189f331/hw-7/src/components/ReviewList/ReviewList.tsx#L14-L23
Когда у меня 10 отзывов мне приходится листать в самый низ, чтобы посмотреть самый свежий.
Как это можно решить?

**Comment by danilovvvladimir** [comment]
Исправил. Поправил логику добавления нового отзыва в массив. Новый отзыв всегда будет располагаться вначале массива.
