### ISSUE TITLE
Комменты к импортам

### ISSUE THREAD

**Issue by AkshachRd** [danilovvvladimir/TL-Practice-2023#47]
Не становится код аккуратнее из-за подписей что это за импорт, а даже наоборот.
Комменты в коде нужны не для того, чтобы они описывали что делает каждая строчка.
Посмотри принцип D.R.Y. Я и так могу видеть что означает `import "./SingleReview.css";` и без комментов.
Если ещё раз так будешь закрывать issue, просто отмахнувшись от моих комментариев своим сниппетом, будет бан 😘.

**Comment by danilovvvladimir** [comment]
Убрал комментарии к импортам.
Не особо шарю как эта тема с issues работает: думал, что как исправлю или обосную просто закрывать. Получается что закрывать должен именно проверяющий, спасибо, приму к сведению.

**Comment by AkshachRd** [comment]
Ты можешь спокойно закрывать issue, если принимаешь коммент как данность. 
Если же есть что возразить, просто отпиши и подожди.
